# Generated by Django 5.0.3 on 2025-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISSOLVED', 'Dissolved')], default='ACTIVE', max_length=10),
        ),
    ]
