# Generated by Django 5.0.3 on 2025-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('ARCHIVED', 'Archived')], default='POSTED', max_length=9),
        ),
    ]
