# Generated by Django 5.0.3 on 2025-03-08 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_announcements_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='branch',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='app.branch'),
        ),
    ]
