# Generated by Django 5.0.3 on 2025-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_announcements_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='min_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
