# Generated by Django 5.0.3 on 2025-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_course_min_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='min_capacity',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
    ]
