# Generated by Django 5.0.3 on 2025-03-23 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_course_min_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matching_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.userprofile')),
            ],
        ),
    ]
