# Generated by Django 5.0.3 on 2025-03-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_matchinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinglog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchinglog',
            name='matching_id',
            field=models.IntegerField(),
        ),
    ]
